# Generated by Django 3.2.9 on 2021-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(max_length=100),
        ),
    ]
